FROM node:22 AS build

WORKDIR /app

COPY package.json /app/
COPY package-lock.json /app/
COPY tsconfig.json /app/
COPY src /app/src/

RUN npm install --production
RUN npm install --only=dev  # Para instalar dependências de desenvolvimento

EXPOSE 3000

CMD ["npm", "run", "dev"]
